name: shared
description: A dart package which holds protos definition and generated code therefore.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  grpc: ^3.1.0
  protobuf: ^2.1.0
  path: ^1.8.2
  envied: ^0.3.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  build_runner:

