// This file is "model.dart"
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'image.schema.dart';

@Model(
  tableName: 'images',
  indexes: <TableIndex>[
    TableIndex(
      name: 'fileName',
      columns: <String>['file_name'],
      unique: true,
    ),
  ],
)
abstract class Image {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get fileName;
  String get fileExtension;
  DateTime get createdAt;
}
