// This file is "model.dart"
import 'package:backend/src/db/models/image.dart';
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'news.schema.dart';

@Model(
  tableName: 'news',
  indexes: <TableIndex>[
    TableIndex(
      name: 'name',
      columns: <String>['name'],
      unique: true,
    ),
  ],
)
abstract class News {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get name;
  String get shortDescription;
  String get text;
  Image? get image;
  DateTime get createdAt;
}
