// This file is "model.dart"
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'user.schema.dart';

@Model(
  tableName: 'users',
  indexes: <TableIndex>[
    TableIndex(
      name: 'email',
      columns: <String>['email'],
      unique: true,
    ),
  ],
)
abstract class User {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String? get firstName;
  String? get lastName;
  String get email;
  String get password;
  DateTime? get birthDate;
}
