name: backend
description: A grpc backend
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  shared:
    path: ../shared
  stormberry: ^0.13.0
  conduit_password_hash: ^4.3.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  build_runner:
  envied_generator:
  dart_code_metrics:
